name = "The Finest Creations"
author = "Treeway7"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f08d3bd51c526c3f4a1f441b593ea80865b59b13cd3d9afa481f910f130ca221"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
